monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - response
        - endpoint
        - cmd
when@dev:
    monolog:
        handlers:
            main:
                type: group
                members: [log_error, log_debug]
            log_error:
                type: fingers_crossed
                action_level: error
                buffer_size: 100
                excluded_http_codes: [400, 401, 403, 405]
                handler: log_error_group
            log_error_group:
                type: group
                members: [log_error_file]
            log_error_file:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/error.log"
                level: debug
                max_files: 2
            log_debug:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/debug.log"
                level: debug
                max_files: 2
            logging_requests:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/request.log"
                level: debug
                max_files: 2
                channels: [ 'request', 'response', "endpoint" ]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            cmd:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/cmd.log"
                level: debug
                max_files: 2
                channels: [ 'cmd' ]
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            logging_requests:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/request.log"
                level: debug
                max_files: 1
                channels: [ 'request', 'response', "endpoint" ]
            cmd:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/cmd.log"
                level: debug
                max_files: 1
                channels: [ 'cmd' ]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            logging_requests:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/request.log"
                level: debug
                max_files: 15
                channels: [ 'request', 'response', "endpoint" ]
            cmd:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/cmd.log"
                level: debug
                max_files: 15
                channels: [ 'cmd' ]